import { 
  apptizers, 
  arabic, 
  biryani, 
  breakFast, 
  burger, 
  cake, 
  chicken, 
  coffee, 
  desserts, 
  fatayer, 
  freshJuices, 
  grilled, 
  iceCream, 
  kebab, 
  mandi, 
  pasta, 
  salad, 
  sandwiches, 
  sashimi, 
  seaFood, 
  soups, 
  starters, 
  sushi, 
  tea 
} from "@/assets/cuisineImages";

const menuItems = [
  {name: 'fresh Juices', image: freshJuices},
  {name: 'coffee', image: coffee},
  {name: 'grilled', image: grilled},
  {name: 'ice Cream', image: iceCream},
  {name: 'sushi', image: sushi},
  {name: 'cakes', image: cake},
  {name: 'chicken', image: chicken},
  {name: 'appetizers', image: apptizers},
  {name: 'starters', image: starters},
  {name: 'desserts', image: desserts},
  {name: 'arabic', image: arabic},
  {name: 'seaFood', image: seaFood},
  {name: 'pasta', image: pasta},
  {name: 'burgers', image: burger},
  {name: 'salad', image: salad},
  {name: 'fatayer', image: fatayer},
  {name: 'kebab', image: kebab},
  {name: 'breakFast', image: breakFast},
  {name: 'mandi', image: mandi},
  {name: 'sandwiches', image: sandwiches},
  {name: 'sashimi', image: sashimi},
  {name: 'biryani', image: biryani},
  {name: 'soups', image: soups},
  {name: 'tea', image: tea},

]

export default menuItems;
